server:
   port: 8081
 
spring:
   application:
      name: demo-rest 
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo_rest
      username: root
      password: root
   jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true